# Generated by Django 3.1.5 on 2021-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachada_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='token_sesion',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
