# Generated by Django 3.1.5 on 2021-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachada_rest', '0002_auto_20210119_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contrasena_hmac',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='salt',
            field=models.BinaryField(default=b'\xacB\xbb)9E:\x8av\xe8p\x96\xa9d\nRv\x0bk\x7f7<KD\x8c\x12\x17\x11\x0e\x0co5'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='token_sesion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
