# Generated by Django 3.1.5 on 2021-02-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachada_rest', '0002_auto_20210119_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contrasena_hmac',
            field=models.BinaryField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='salt',
            field=models.BinaryField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='token_sesion',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
