# Generated by Django 3.1.5 on 2021-02-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachada_rest', '0003_auto_20210208_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contrasena_hmac',
            new_name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='token_sesion',
        ),
    ]
