# Generated by Django 3.1.5 on 2021-02-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachada_rest', '0003_auto_20210208_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='token_sesion',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='salt',
            field=models.BinaryField(default=b"\x9a\xf8\x16y\x8e'DC\x99O\xd7\xc3\xa6\x1c\x8e\x1e\xe6\xf1+\xe7\xd6\xfd\xd8\xe7\x8a\xac?\xf9\xcft6\x1f"),
        ),
    ]
