# Generated by Django 3.1.5 on 2021-02-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachada_rest', '0005_auto_20210209_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contrasena_hmac',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
