# Generated by Django 3.1.5 on 2021-02-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachada_rest', '0006_auto_20210209_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contrasena_hmac',
            new_name='contrasena',
        ),
    ]
